name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [14.x, 15.x]
                os: [ubuntu-latest, macOS-latest] # There isn't a redis image that supports all the OS's sadly

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Setup Redis
              uses: shogo82148/actions-setup-redis@v1
              with:
                  redis-version: "6.x"

            - name: Setup Postgresql
              uses: harmon758/postgresql-action@v1
              with:
                  postgresql version: "12.6"
                  postgresql user: "beatzoid"
                  postgresql password: "beatzoid"
                  postgresql db: "airbnb-testing"

            - name: Install Dependencies
              run: yarn install

            - name: Run Tests
              run: yarn test
